<?php

namespace AppBundle\Repository;

/**
 * MergedFeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MergedFeedRepository extends \Doctrine\ORM\EntityRepository
{
}
